{% set name = "entt" %}
{% set version = "3.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/skypjack/entt/archive/v{{ version }}.tar.gz
  sha256: e31f6e95a30e2977a50449ef9a607a9ff40febe6f9da2a8144a183f8606f7719

build:
  number: 1

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake
    - gtest  # [build_platform == target_platform]
    - ninja  # [not win]

test:
  commands:
    - test -d ${PREFIX}/include/entt  # [unix]
    - test -f ${PREFIX}/lib/EnTT/cmake/EnTTTargets.cmake  # [unix]
    - if not exist %PREFIX%\\Library\\include\\entt exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\EnTT\cmake\\EnTTTargets.cmake exit 1  # [win]

about:
  home: https://github.com/skypjack/entt/wiki
  summary: Gaming meets modern C++ - a fast and reliable entity component system (ECS) and much more
  description: |
    `EnTT` is a header-only, tiny and easy to use library for game programming and
    much more written in **modern C++**.<br/>
    [Among others](https://github.com/skypjack/entt/wiki/EnTT-in-Action), it's used
    in [**Minecraft**](https://minecraft.net/en-us/attribution/) by Mojang, the
    [**ArcGIS Runtime SDKs**](https://developers.arcgis.com/arcgis-runtime/) by Esri
    and the amazing [**Ragdoll**](https://ragdolldynamics.com/).<br/>
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jslee02
    - jeongseok-meta
